version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=questions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=questions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5