"""init

Revision ID: 010068eec51f
Revises: 
Create Date: 2023-05-18 17:41:05.281136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010068eec51f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_from_site', sa.Integer(), nullable=True),
    sa.Column('q_text', sa.Text(), nullable=True),
    sa.Column('q_answer', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_from_site')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
